global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "Monitoring"

scrape_configs:
  - job_name: "liteprotocoltester"
    static_configs:
    - targets: ["lpt-runner-publishernode:8003",
                "lpt-runner-publishernode-1:8003",
                "lpt-runner-publishernode-2:8003",
                "lpt-runner-publishernode-3:8003",
                "lpt-runner-publishernode-4:8003",
                "lpt-runner-publishernode-5:8003",
                "lpt-runner-publishernode-6:8003",
                "lpt-runner-publishernode-7:8003",
                "lpt-runner-publishernode-8:8003",
                "lpt-runner-publishernode-9:8003",
                "lpt-runner-publishernode-10:8003",
                "lpt-runner-publishernode-11:8003",
                "lpt-runner-publishernode-12:8003",
                "lpt-runner-publishernode-13:8003",
                "lpt-runner-publishernode-14:8003",
                "lpt-runner-publishernode-15:8003",
                "lpt-runner-publishernode-16:8003",
                "lpt-runner-publishernode-17:8003",
                "lpt-runner-publishernode-18:8003",
                "lpt-runner-publishernode-19:8003",
                "lpt-runner-receivernode:8003",
                "lpt-runner-receivernode-1:8003",
                "lpt-runner-receivernode-2:8003",
                "lpt-runner-receivernode-3:8003",
                "lpt-runner-receivernode-4:8003",
                "lpt-runner-receivernode-5:8003",
                "lpt-runner-receivernode-6:8003",
                "lpt-runner-receivernode-7:8003",
                "lpt-runner-receivernode-8:8003",
                "lpt-runner-receivernode-9:8003",
                "lpt-runner-receivernode-10:8003",
                "lpt-runner-receivernode-11:8003",
                "lpt-runner-receivernode-12:8003",
                "lpt-runner-receivernode-13:8003",
                "lpt-runner-receivernode-14:8003",
                "lpt-runner-receivernode-15:8003",
                "lpt-runner-receivernode-16:8003",
                "lpt-runner-receivernode-17:8003",
                "lpt-runner-receivernode-18:8003",
                "lpt-runner-receivernode-19:8003",
                "lpt-publishernode:8003",
                "lpt-publishernode-1:8003",
                "lpt-publishernode-2:8003",
                "lpt-publishernode-3:8003",
                "lpt-publishernode-4:8003",
                "lpt-publishernode-5:8003",
                "lpt-publishernode-6:8003",
                "lpt-publishernode-7:8003",
                "lpt-publishernode-8:8003",
                "lpt-publishernode-9:8003",
                "lpt-publishernode-10:8003",
                "lpt-publishernode-11:8003",
                "lpt-publishernode-12:8003",
                "lpt-publishernode-13:8003",
                "lpt-publishernode-14:8003",
                "lpt-publishernode-15:8003",
                "lpt-publishernode-16:8003",
                "lpt-publishernode-17:8003",
                "lpt-publishernode-18:8003",
                "lpt-publishernode-19:8003",
                "lpt-receivernode:8003",
                "lpt-receivernode-1:8003",
                "lpt-receivernode-2:8003",
                "lpt-receivernode-3:8003",
                "lpt-receivernode-4:8003",
                "lpt-receivernode-5:8003",
                "lpt-receivernode-6:8003",
                "lpt-receivernode-7:8003",
                "lpt-receivernode-8:8003",
                "lpt-receivernode-9:8003",
                "lpt-receivernode-10:8003",
                "lpt-receivernode-11:8003",
                "lpt-receivernode-12:8003",
                "lpt-receivernode-13:8003",
                "lpt-receivernode-14:8003",
                "lpt-receivernode-15:8003",
                "lpt-receivernode-16:8003",
                "lpt-receivernode-17:8003",
                "lpt-receivernode-18:8003",
                "lpt-receivernode-19:8003",
                "publishernode-1:8003",
                "publishernode-2:8003",
                "publishernode-3:8003",
                "publishernode-4:8003",
                "publishernode-5:8003",
                "publishernode-6:8003",
                "receivernode-1:8003",
                "receivernode-2:8003",
                "receivernode-3:8003",
                "receivernode-4:8003",
                "receivernode-5:8003",
                "receivernode-6:8003",]
